/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who the bearer token says you are, and whether auth is on at all.
         *
         *     Answers anonymous callers on purpose: it is how the console learns
         *     whether to show a sign-in. It discloses only that auth is enabled.
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenarios */
        get: operations["get_scenarios_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{scenario_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario Events */
        get: operations["get_scenario_events_scenarios__scenario_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_investigations__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Investigation
         * @description Live progress for one investigation, as server-sent events.
         *
         *     Carries progress only. The case file is fetched over REST once `done`
         *     arrives, so there is one authoritative representation of it.
         */
        get: operations["stream_investigation_investigations__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{job_id}/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Resolve one citation from a finished run back to what the agent fetched.
         */
        get: operations["get_evidence_investigations__job_id__evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/techniques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Techniques
         * @description Find ATT&CK techniques by meaning, by shared words, or both.
         *
         *     Defaults to hybrid when a dense channel is configured and lexical when it
         *     is not, so a bare checkout still answers.
         */
        get: operations["search_techniques_search_techniques_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{job_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Review
         * @description Record agreement or disagreement with a case file.
         *
         *     Never mutates the case file: a review is an observation about what the
         *     agent said on that run, and the run's record stays as it was.
         */
        post: operations["add_review_investigations__job_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Reviews
         * @description Candidate eval cases for a human to curate.
         *
         *     Export rather than a direct write into the dev split: letting the
         *     agent's own output become its answer key is the contamination the eval
         *     protocol exists to prevent.
         */
        get: operations["export_reviews_reviews_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttackTechnique */
        AttackTechnique: {
            /** Technique Id */
            technique_id: string;
            /** Name */
            name: string;
            /** Tactics */
            tactics: string[];
            /** Description */
            description: string;
        };
        /** CreateInvestigationRequest */
        CreateInvestigationRequest: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Model
             * @default ollama
             * @enum {string}
             */
            model: "ollama" | "local-7b" | "openai" | "teacher" | "replay" | "scripted";
            /**
             * Sync
             * @default false
             */
            sync: boolean;
        };
        /**
         * EvalCaseCandidate
         * @description What a curator would paste into a scenario manifest, not a gold label.
         */
        EvalCaseCandidate: {
            /** Scenario Id */
            scenario_id: string;
            /** Agent Verdict */
            agent_verdict: string;
            /**
             * Proposed Verdict
             * @enum {string}
             */
            proposed_verdict: "malicious" | "suspicious" | "likely_benign" | "not_enough_evidence";
            /** Note */
            note: string;
            /** Reviewer */
            reviewer: string;
            /** Created At */
            created_at: string;
            /** Source Job Id */
            source_job_id: string;
        };
        /**
         * Event
         * @description One normalized telemetry event. Flat on purpose: it is rendered to an LLM as-is.
         */
        Event: {
            /** Event Id */
            event_id: string;
            kind: components["schemas"]["EventKind"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Host */
            host: string;
            /** User */
            user?: string | null;
            /** Pid */
            pid?: number | null;
            /** Ppid */
            ppid?: number | null;
            /** Image */
            image?: string | null;
            /** Command Line */
            command_line?: string | null;
            /** Parent Image */
            parent_image?: string | null;
            /** Parent Command Line */
            parent_command_line?: string | null;
            /** Sha256 */
            sha256?: string | null;
            /** Target Pid */
            target_pid?: number | null;
            /** Target Image */
            target_image?: string | null;
            /** Target Path */
            target_path?: string | null;
            /** Details */
            details?: string | null;
            /** Dest Ip */
            dest_ip?: string | null;
            /** Dest Port */
            dest_port?: number | null;
            /** Dest Host */
            dest_host?: string | null;
            /** Query */
            query?: string | null;
            /**
             * Source
             * @default sysmon
             */
            source: string;
            /** Source Event Code */
            source_event_code?: number | null;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "process_create" | "network_connect" | "image_load" | "process_access" | "file_create" | "registry_set" | "dns_query" | "service_install" | "scheduled_task";
        /** EventPage */
        EventPage: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Limit */
            limit: number;
        };
        /**
         * EvidenceResolution
         * @description One resolved citation. Exactly one of the payload fields is populated.
         */
        EvidenceResolution: {
            /** Evidence Id */
            evidence_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "event" | "sigma_rule" | "attack_technique";
            /** First Seen Tool Seq */
            first_seen_tool_seq?: number | null;
            event?: components["schemas"]["Event"] | null;
            rule?: components["schemas"]["SigmaRule"] | null;
            technique?: components["schemas"]["AttackTechnique"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hit */
        Hit: {
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "attack_technique" | "sigma_rule";
            /** Score */
            score: number;
            /** Rank */
            rank: number;
            /** Channel Ranks */
            channel_ranks?: {
                [key: string]: number;
            };
        };
        /** InvestigationJobResponse */
        InvestigationJobResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Scenario Id */
            scenario_id: string;
            /** Model */
            model: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Review */
        Review: {
            /** Id */
            id: string;
            /** Job Id */
            job_id: string;
            /** Scenario Id */
            scenario_id: string;
            /** Agent Verdict */
            agent_verdict: string;
            /** Agrees */
            agrees: boolean;
            /** Corrected Verdict */
            corrected_verdict: ("malicious" | "suspicious" | "likely_benign" | "not_enough_evidence") | null;
            /** Note */
            note: string;
            /** Reviewer */
            reviewer: string;
            /** Created At */
            created_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Agrees */
            agrees: boolean;
            /** Corrected Verdict */
            corrected_verdict?: ("malicious" | "suspicious" | "likely_benign" | "not_enough_evidence") | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ScenarioDetail
         * @description Queue row plus the boxed window. Still no events and still no gold.
         */
        ScenarioDetail: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Split
             * @enum {string}
             */
            split: "dev" | "test";
            /**
             * Origin
             * @enum {string}
             */
            origin: "otrf" | "authored";
            /**
             * Description
             * @default
             */
            description: string;
            /** Alert Id */
            alert_id: string;
            /** Host */
            host: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Title */
            rule_title: string;
            severity: components["schemas"]["Severity"];
            /**
             * Fired At
             * Format: date-time
             */
            fired_at: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Trigger Event Id */
            trigger_event_id: string;
            /** Event Count */
            event_count: number;
        };
        /**
         * ScenarioSummary
         * @description One alert-queue row. Alert metadata only — never events, never gold.
         */
        ScenarioSummary: {
            /** Scenario Id */
            scenario_id: string;
            /**
             * Split
             * @enum {string}
             */
            split: "dev" | "test";
            /**
             * Origin
             * @enum {string}
             */
            origin: "otrf" | "authored";
            /**
             * Description
             * @default
             */
            description: string;
            /** Alert Id */
            alert_id: string;
            /** Host */
            host: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Title */
            rule_title: string;
            severity: components["schemas"]["Severity"];
            /**
             * Fired At
             * Format: date-time
             */
            fired_at: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "lexical" | "dense" | "hybrid";
            /** Available Modes */
            available_modes: ("lexical" | "dense" | "hybrid")[];
            /** Hits */
            hits: components["schemas"]["Hit"][];
            /** Corpus Source */
            corpus_source: string;
            /** N Techniques */
            n_techniques: number;
            /** Catalog Revision */
            catalog_revision?: string | null;
            /** Embedder */
            embedder?: string | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /** SigmaRule */
        SigmaRule: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Level */
            level: string;
            /** Tags */
            tags?: string[];
            /** Falsepositives */
            falsepositives?: string[];
            /** References */
            references?: string[];
            /** Detection */
            detection?: {
                [key: string]: unknown;
            };
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_scenarios_scenarios_get: {
        parameters: {
            query?: {
                split?: ("dev" | "test") | null;
                severity?: ("low" | "medium" | "high" | "critical") | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_events_scenarios__scenario_id__events_get: {
        parameters: {
            query?: {
                pid?: number | null;
                kind?: components["schemas"]["EventKind"][] | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_investigations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationJobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_investigations__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_investigation_investigations__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_investigations__job_id__evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_techniques_search_techniques_get: {
        parameters: {
            query: {
                q: string;
                mode?: ("lexical" | "dense" | "hybrid") | null;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_review_investigations__job_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reviews_reviews_get: {
        parameters: {
            query?: {
                scenario_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_reviews_reviews_export_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalCaseCandidate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
